### PR TITLE
Dockerfile_yocto-build-env: Add screen

### PR DESCRIPTION
**Pull request by ajlennon**
To enable us to use `bitbake -c devshell foo` in container

### CODE REVIEW

**Comment by ajlennon** [comment]
@alexgg could anybody take a quick look please?

**Review by alexgg — APPROVED** [review]

**Comment by alexgg** [comment]
@ajlennon would you please add a `Change-type: patch` footer? The CI needs this to pass.

**Comment by ajlennon** [comment]
Done @alexgg

**Comment by alexgg** [comment]
Pending on https://github.com/balena-os/balena-yocto-scripts/pull/318

**Comment by alexgg** [comment]
thanks @ajlennon sorry to bother you again - would you mind rebasing over master again? I had to enable external contributions to this repository in our CI/CD system.

**Comment by ajlennon** [comment]
I just clicked "Update branch" here. Did that help? :)

**Comment by ajlennon** [comment]
Rebasing always scares me a bit. OK how about now?

**Pull request merged**
