### PR TITLE
Add docker-balena scripts library and update docker version in build-env

### PR DESCRIPTION
**Pull request by alexgg**
There are multiple scripts that need to start a docker daemon. Instead of duplicating code add a single include file with the functionality. To use common code, update the docker binary in build-env too.

### CODE REVIEW

**Comment by alexgg** [comment]
Tested with tests jobs for yocto-raspberrypi4-64 (overlay) and raspberrypi3 (aufs)

**Comment by alexgg** [comment]
Pending to test the changes to the push-os-version helper container.

**Comment by alexgg** [comment]
Tested locally that the `balena-push-os-version.sh` script is able to start, wait and stop the dockerd daemon.

**Review by klutchell — APPROVED** [review]
lgtm

**Pull request merged**
